server{
    listen 80 ;
    root /usr/share/nginx/html;
    index index.html;

    # React frontend
    location / {
        try_files $uri /index.html;
    }
    
    # backend (Django)
    location /api/{
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # djago admin & static files
    location /admin/{
        proxy_pass http://backend:8000;
       
    }

    location /static/{
        proxy_pass http://backend:8000;
    }

    location /media/{
        proxy_pass http://backend:8000;
    }




}